# Generated by Django 6.0.6 on 2026-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_sale_product_sale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('products', models.ManyToManyField(related_name='categories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
