# Generated by Django 6.0.6 on 2026-08-13 16:04

from django.db import migrations, models


def generate_order_numbers(apps, schema_editor):
    Order = apps.get_model('products', 'Order')

    orders = Order.objects.order_by('date_created')

    for number, order in enumerate(orders, start=1001):
        order.order_number = number
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        (
            'products',
            '0006_order_address_order_city_order_full_name_order_phone_and_more'
        ),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
            ),
        ),

        migrations.RunPython(
            generate_order_numbers,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(
                editable=False,
                unique=True,
            ),
        ),

    ]