# Generated by Django 6.0.6 on 2026-09-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_orderitem_product_alter_product_price_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
